version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/*"
      - "/tests/*"
      - "/tools/*"
    schedule:
      interval: "weekly"
    groups:
      nuget-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
      nuget-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"
